#!/bin/bash
# requires: avprobe, ffmpeg, transcode

function bitrate () {
    BITRATE=$(avprobe -show_format $filename 2> /dev/null | grep bit_rate | sed "s/.*bit_rate=\([0-9]\+\).*/\1/g")
    BITRATE=$(($BITRATE/1024))
}
function resolution () {
    RES=$(ffmpeg -i $filename 2>&1 | grep Stream | grep -oP ', \K[0-9]+x[0-9]+')
}

for filename in "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"; do
    if [ "$filename" = "" || "$filename" = " " ]; then
        exit
    else
        FILE=$(basename "$1")
        bitrate "$filename"
        resolution "$filename"

        gdialog --title "Job started" --msgbox "\nJob started! I will tell you when I'm done." 200 300
        transcode -Z $RES,fast -J stabilize -i "$FILE"
        transcode -Z $RES,fast -J transform -i "$FILE" -y xvid4 -w $BITRATE,250,100 -o "ok_$FILE"
        rm "$FILE.trf"
        gdialog --title "Done!" --msgbox "\n$FILE deshaken!" 200 300
    fi
done
